#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "textarea"
name = "Textarea"
description.en = "Notes webapp"
description.fr = "Application web pour prendre des notes"

version = "1.0.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0-only"
website = "https://textarea.my/"
demo = "https://textarea.my/"
code = "https://github.com/antonmedv/textarea"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/textarea"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/antonmedv/textarea/archive/refs/tags/v1.0.0.tar.gz"
    sha256 = "c45553b24c219492c0759ac982bb29d0314e05b55406ebfd5b05dc93352a10cc"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
